include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan.yml

stages:
  - download
  - build
  - scan

variables:
  GPG_KEY: "0482D84022F52DF1C4E7CD43293ACD0907D9495A"
  ARC: x86_64
  VERSION: 3.10.0
  EXTRA_TAGS: 'latest 3.10'
  DOCKER_BUILDKIT: 1

download:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  before_script:
    - apk add --no-cache gnupg curl grep
    - |
        gpg --keyserver pgp.mit.edu --recv-keys "${GPG_KEY}" ||
        gpg --keyserver keyserver.pgp.com --recv-keys "${GPG_KEY}" ||
        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "${GPG_KEY}"
  script:
    - VERSION_SHORT=$(echo ${VERSION} | grep -oP '(\d+[.]\d+)')
    - echo ${VERSION_SHORT}
    - curl -OsS "https://ftp.acc.umu.se/mirror/alpinelinux.org/${VERSION_SHORT}/releases/${ARC}/alpine-minirootfs-${VERSION}-${ARC}.tar.gz"
    - curl -OsS "https://ftp.acc.umu.se/mirror/alpinelinux.org/${VERSION_SHORT}/releases/${ARC}/alpine-minirootfs-${VERSION}-${ARC}.tar.gz.sha256"
    - curl -OsS "https://ftp.acc.umu.se/mirror/alpinelinux.org/${VERSION_SHORT}/releases/${ARC}/alpine-minirootfs-${VERSION}-${ARC}.tar.gz.asc"
    - gpg --verify alpine-minirootfs-${VERSION}-${ARC}.tar.gz.asc alpine-minirootfs-${VERSION}-${ARC}.tar.gz
    - grep " alpine-minirootfs-${VERSION}-${ARC}.tar.gz\$" alpine-minirootfs-${VERSION}-${ARC}.tar.gz.sha256 | sha256sum -c -
    - mv alpine-minirootfs-${VERSION}-${ARC}.tar.gz alpine-minirootfs.tar.gz
  artifacts:
    paths:
      - alpine-minirootfs.tar.gz
    expire_in: 1 days

build:
  stage: build
  image: docker:latest
  dependencies:
    - download
  services:
    - docker:dind
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - VERSION_SHORT=$(echo ${VERSION} | grep -oP '(\d+[.]\d+)')
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --build-arg VERSION_SHORT=${VERSION_SHORT} --build-arg VERSION=${VERSION} --build-arg ARC=${ARC} .
    - docker build -t ${CI_REGISTRY_IMAGE}/buildbase:${CI_COMMIT_SHA} -f buildbase.dockerfile .
    - TAGS="${VERSION} ${EXTRA_TAGS}"
    - |
      for tag in ${TAGS}; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/alpine:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}/buildbase:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/buildbase:${tag}
        docker push jitesoft/alpine:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
        docker push ${CI_REGISTRY_IMAGE}/buildbase:${tag}
      done
  tags:
    - jitesoft
