include:
  - local: /.gitlab/build.yml
  - file: /Scan/trivy.yml
    project: jitesoft/gitlab-ci-lib

stages:
  - check
  - download
  - verify
  - build
  - scan
  - create-cache

variables:
  ARCHITECTURES: "x86_64 armv7 aarch64 ppc64le s390x x86"

check-version:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: never
  stage: check
  cache:
    key: alpine-version
    paths:
      - version.txt
    policy: pull
  script:
    - apk add --no-cache wget grep curl
    - VERSION=$(wget -qO- https://alpinelinux.org/downloads/ | grep -oP "(?<=<strong>)(([0-9]{0,3}(\.?)){3})" | awk 'NR==1{print $1}')
    - touch version.txt
    - |
      if [ "$(cat version.txt)" != "${VERSION}" ]; then
        echo "Should build new container."
        curl -F token=${CI_JOB_TOKEN} -F ref=master -F "variables[ALPINE_VERSION]=${VERSION}" -F "variables[BUILD]=true" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline
      else
        curl -F token=${CI_JOB_TOKEN} -F ref=master -F "variables[SCAN]=true" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline
      fi
