include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan.yml

stages:
  - download
  - build
  - scan

variables:
  GPG_KEY: "0482D84022F52DF1C4E7CD43293ACD0907D9495A"
  VERSION: 3.10.2
  TARGET_PLATFORMS: "aarch64 x86_64 armv7"
  EXTRA_TAGS: 'latest 3.10'
  DOCKER_BUILDKIT: 1

download:
  image: registry.gitlab.com/jitesoft/dockerfiles/alpine:latest
  stage: download
  before_script:
    - apk add --no-cache gnupg curl grep
    - chmod +x target.sh
    - |
        gpg --keyserver pgp.mit.edu --recv-keys "${GPG_KEY}" ||
        gpg --keyserver keyserver.pgp.com --recv-keys "${GPG_KEY}" ||
        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "${GPG_KEY}"
  script:
    - VERSION=$(wget -qO- https://alpinelinux.org/downloads/ | grep -oP "(?<=<strong>)(([0-9]{0,3}(\.?)){3})" | awk 'NR==1{print $1}')
    - VERSION_SHORT=$(echo ${VERSION} | grep -oP '(\d+[.]\d+)')
    - |
      for ARCH in ${TARGET_PLATFORMS}; do
          BUILDX_ARCH=$(./target.sh ${ARCH})
          echo "Downloading for ${BUILDX_ARCH} (${ARCH})."
          mkdir -p alpine/${BUILDX_ARCH}
          curl -OsS "https://ftp.acc.umu.se/mirror/alpinelinux.org/v${VERSION_SHORT}/releases/${ARCH}/alpine-minirootfs-${VERSION}-${ARCH}.tar.gz"
          curl -OsS "https://ftp.acc.umu.se/mirror/alpinelinux.org/v${VERSION_SHORT}/releases/${ARCH}/alpine-minirootfs-${VERSION}-${ARCH}.tar.gz.sha256"
          curl -OsS "https://ftp.acc.umu.se/mirror/alpinelinux.org/v${VERSION_SHORT}/releases/${ARCH}/alpine-minirootfs-${VERSION}-${ARCH}.tar.gz.asc"
          gpg --verify alpine-minirootfs-${VERSION}-${ARCH}.tar.gz.asc alpine-minirootfs-${VERSION}-${ARCH}.tar.gz
          grep " alpine-minirootfs-${VERSION}-${ARCH}.tar.gz\$" alpine-minirootfs-${VERSION}-${ARCH}.tar.gz.sha256 | sha256sum -c -
          mv alpine-minirootfs-${VERSION}-${ARCH}.tar.gz alpine/${BUIDX_ARCH}/alpine-minirootfs.tar.gz
      done;
  artifacts:
    paths:
      - alpine/
    expire_in: 1 days

build:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/docker/buildx:latest
  dependencies:
    - download
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - apt-get install -y wget grep
  script:
    - VERSION=$(wget -qO- https://alpinelinux.org/downloads/ | grep -oP "(?<=<strong>)(([0-9]{0,3}(\.?)){3})" | awk 'NR==1{print $1}')
    - VERSION_SHORT=$(echo ${VERSION} | grep -oP '(\d+[.]\d+)')
    - docker buildx create --name buildx-test --platform linux/amd64,linux/arm64,linux/arm/v8,linux/arm/v7 --use
    - docker buildx inspect --bootstrap buildx-test
    - docker buildx build --load --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} --build-arg VERSION_SHORT=${VERSION_SHORT} --build-arg VERSION=${VERSION} .
    - docker buildx build --load --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${CI_REGISTRY_IMAGE}/buildbase:${CI_COMMIT_SHA} -f buildbase.dockerfile .
    - TAGS="${VERSION} ${EXTRA_TAGS}"
    - |
      for tag in ${TAGS}; do
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} jitesoft/alpine:${tag}
        docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:${tag}
        docker tag ${CI_REGISTRY_IMAGE}/buildbase:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}/buildbase:${tag}
        docker push jitesoft/alpine:${tag}
        docker push ${CI_REGISTRY_IMAGE}:${tag}
        docker push ${CI_REGISTRY_IMAGE}/buildbase:${tag}
      done
  tags:
    - jitesoft
    - arm64

scan:
  stage: scan
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
